### ISSUE TITLE
color not showing in tablist

### ISSUE THREAD

**Issue by Daynios** [Leeeunderscore/LeeesNC#8]
hey, i am using the plugin on a 1.18 server, and when i do the nc command, the color does apply to my name in chat, but cannot be seen in the tablist. could anyone help?
![image](https://user-images.githubusercontent.com/64890512/150484165-f172d2ed-6a22-49c7-a556-c3356b11f949.png)
![image](https://user-images.githubusercontent.com/64890512/150484175-5ea7252d-6f90-49c9-beec-51ce8780eed5.png)

**Comment by CEOofYT** [comment]
did you resolved it?
